import './globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className='h-14 bg-gray-700'>
                    <h1 className='flex itens-center py-2 justify-center text-white text-2xl'>CineWeb</h1>
                </div>
                {children}
            </body>
        </html>
    )
}
